#!/bin/bash
runuser -l hypercube -m -c "export AWS_CONTAINER_CREDENTIALS_RELATIVE_URI=$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI && export PAPP_BASE_URL=$PAPP_BASE_URL && export PAPP_LISTENING_PORT=$PAPP_LISTENING_PORT && export DATA_BUCKET_NAME=$DATA_BUCKET_NAME && export DATA_FILE_PATH=$DATA_FILE_PATH && python3.6 ./app.py"
